### ISSUE TITLE
`theme pull` in a non-empty and non-theme directory hangs on CI environment (even with `SHOPIFY_CLI_TTY`)

### ISSUE THREAD

**Issue by josephfinlayson** [Shopify/cli#1136]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

`shopify theme pull` being run in a non-theme directory and in an CI/CD environment (→ [docs](https://shopify.dev/themes/tools/cli/ci-cd#example-github-actions)) should display confirmation dialogue _It doesn’t seem like you’re running this command in a theme directory. Are you sure you want to proceed?_ and not hang if `SHOPIFY_CLI_TTY` is set to `0`.

### Actual behavior

`theme pull` hangs, never completes, and displays no further message.

### Stack trace

```shell
[STARTED] Installing theme dependencies
2023-01-18T11:19:35.391Z: 
Running system process:
  · Command: ruby -v
  · Working directory: /home/runner/work/shopify-theme/shopify-theme

2023-01-18T11:19:35.417Z: 
Running system process:
  · Command: bundle -v
  · Working directory: /home/runner/work/shopify-theme/shopify-

…

2023-01-18T11:19:35.747Z: 
Running system process:
  · Command: bundle install
  · Working directory: /home/runner/.cache/shopify-cli-nodejs/vendor/ruby-cli/2.34.0

[SUCCESS] Installing theme dependencies
2023-01-18T11:19:48.295Z: 
Running system process:
  · Command: bundle exec shopify theme pull /home/runner/work/shopify-theme/shopify-theme --theme 140280135974
  · Working directory: /home/runner/work/shopify-theme/shopify-theme
```

### Reproduction steps

Create a github actions file with following settings

```yaml
name: Theme deploy

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: 'latest'
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme
      - name: Deploy
        env:
          # Store URL, like your-store.myshopify.com
          SHOPIFY_FLAG_STORE: '${{ secrets.SHOPIFY_STORE }}'
          # Password generated from Theme Access app
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_CLI_TTY: 0
        run: shopify theme push --path ./path/to/your/theme --theme your-theme-name-or-id
```

Populate the secrets
and attempt to deploy

### Operating System

Github Actions 

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.34

**Comment by amcaplan** [comment]
cc @Shopify/theme-developer-tools

**Comment by josephfinlayson** [comment]
One not that might help triage. `shopify theme list` works!

**Comment by Poitrin** [comment]
I created a fresh repository with the following workflow:

```yml
name: Theme deploy

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: 'latest'
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme
      - name: Deploy
        env:
          SHOPIFY_FLAG_STORE: '${{ secrets.SHOPIFY_STORE }}'
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_CLI_TTY: 0
        run: shopify theme pull --theme 129282670648 --verbose
```

The ID `129282670648` belongs to my _live_ theme (based on Dawn).

Unfortunately, I was not able to reproduce your issue – `shopify theme pull` completed successfully with message `Theme pulled successfully.` (not visible in screenshot).
 
![theme-pull-debug](https://user-images.githubusercontent.com/12963280/216587326-5476fe0e-b511-48d1-b9fe-73d479f6f150.jpg)

Can you share your actual GitHub workflow (or at least the CLI-relevant parts)?
The workflow/link you shared was helpful, but it contained e.g. the `shopify theme push` command.
