### ISSUE TITLE
[Bug]: Generic 422 API client error on `shopify theme push` due to having too many dev themes

### ISSUE THREAD

**Issue by phv-ppuente** [Shopify/cli#1691]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

The Shopify CLI will publish the theme using the same CI/CD configuration that worked yesterday and that works from my local environment. The GitHub Actions console confirms the job was successful and a preview link is added to the GitHub Actions run summary.

### Actual behavior

GitHub Actions console shows "422 API request client error". The dev-deploy step in the action fails. No preview links is provided.

### Verbose output

```shell
2023-03-29T20:39:56.416Z: Running command theme push
  shopify:theme:push init version: @oclif/core@2.1.4 argv: [ '--development', '--verbose' ] +0ms
2023-03-29T20:39:56.442Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2023-03-29T20:39:56.442Z: Getting development theme...
2023-03-29T20:39:56.915Z: Request to https://theme-kit-access.shopifyapps.com/cli/admin/api/unstable/themes.json completed in 458 ms
With response headers:
 - cache-control: no-cache
 - content-type: application/json; charset=utf-8
 - x-request-id: dc9c7cca-7690-4794-abe4-d08ec3e05b9e
    
╭─ ──╮
│ e  │
│ r  │
│ r  │
│ o  │
│ r  │
│    │
│    │
│    │
│    │
│  [ │
│  4 │
│  2 │
│  2 │
│  ] │
│    │
│  A │
│  P │
│  I │
│    │
│  r │
│  e │
│  q │
│  u │
│  e │
│  s │
│  t │
│    │
│  c │
│  l │
│  i │
│  e │
│  n │
│  t │
│    │
│  e │
│  r │
│  r │
│  o │
│  r │
│    │
╰────╯

2023-03-29T20:39:57.073Z: Unable to log analytics event - no information on executed command
Error: Process completed with exit code 1.
```

### Reproduction steps

1. Push a Shopify theme to a GitHub repo
2. Configure a `STAGING_SHOPIFY_THEME_ACCESS_PASSWORD` secret in the GitHub repo (reference https://docs.github.com/en/actions/security-guides/encrypted-secrets). The secret value is a Theme Access password (reference https://shopify.dev/docs/themes/tools/cli/ci-cd#step-1-get-a-theme-access-password-for-the-store)
3. Configure a `STAGING_SHOP_NAME` repository variable with the shop name (reference https://docs.github.com/en/actions/learn-github-actions/variables)
4. Add the following code to a file in `.github/workflows/dev-deploy.yml`:
```
name: Dev Deployment
on:
  workflow_dispatch:

env:
  # Store URL, like your-store.myshopify.com
  SHOPIFY_FLAG_STORE: '${{ vars.STAGING_SHOP_NAME }}.myshopify.com'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: 'latest'
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme
      - name: Get Branch Name
        run: export BRANCH=$(echo "${{ github.ref }}" | sed "s/refs\/heads\///") && echo "branch=$BRANCH" >> $GITHUB_ENV
      - name: Deploy
        # Enable TTY to workaround Shopify CLI error
        shell: 'script -q -e -c "bash {0}"'
        env:
          # Password generated from Theme Access app
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.STAGING_SHOPIFY_THEME_ACCESS_PASSWORD }}
          SHOPIFY_CLI_TTY: 0
        run: SHOPIFY_CLI_BUNDLED_THEME_CLI=1 shopify theme push --development --theme="****/${{ env.branch }}" --verbose > ./push_output.txt
      - name: Get Theme ID
        run: echo "theme_id=$(grep -Po -m 1 "(?<=\/unstable\/themes\/).+(?=\/assets)" ./push_output.txt)" >> $GITHUB_ENV
      - name: Add preview link
        run: echo '::notice title=Preview Link::https://${{ vars.STAGING_SHOP_NAME }}.myshopify.com/?preview_theme_id=${{ env.theme_id }}'
```
6. Push your changes to the main/master branch in your repo, then navigate to Actions > Dev Deploy and trigger a dev deployment.
7. Monitor the GitHub Actions console

Note that I am unable to replicate this symptom with the same environment variable configuration on my local Windows machine.

### Operating System

Ubuntu (Latest)

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

### Shell

Bash

### Node version (run `node -v` if you're not sure)

v18.x.x (current LTS)

**Comment by phv-ppuente** [comment]
It's worth mentioning that I've already uploaded the same repository to a new GitHub repo and I was able to replicate the symptom in the new repository. However, as noted above, the same theme can be pushed with the same commands/config from my local Windows machine which tells me the theme itself is not the problem.

**Comment by phv-ppuente** [comment]
@gonzaloriestra thanks for the context on the 422. I don't think it's too many requests against the same theme access password because the example I posted in https://github.com/Shopify/cli/issues/1691#issuecomment-1490460806 was using a brand new theme access password that is not in use elsewhere.

We do have multiple devs pushing commits frequently which can trigger the deployment pipeline against the same dev store repeatedly. If it were rate limiting, I would normally expect it to be a temporary issue but that doesn't appear to be the case.

**Comment by phv-ppuente** [comment]
I've now reproduced this symptom in a Windows environment in GitHub Actions. Example workflow file:
`.github/workflows/<workflow_id>.yml`
```
name: PR Deployment and Testing
on:
  workflow_dispatch:
  pull_request:
    branches:
      - staging
      - main

defaults:
  run:
    shell: pwsh

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  # Store URL, like your-store.myshopify.com
  SHOPIFY_FLAG_STORE: '${{ vars.STAGING_SHOP_NAME }}.myshopify.com'
  SHOPIFY_CLI_BUNDLED_THEME_CLI: 1 

jobs:
  deploy:
    runs-on: windows-latest

    outputs:
      theme_id: ${{ steps.output_theme_id.outputs.theme_id}}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: 'latest'
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme
      - name: DELETEME Deploy (verbose)
        env:
          # Password generated from Theme Access app
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.STAGING_SHOPIFY_THEME_ACCESS_PASSWORD }}
          SHOPIFY_CLI_TTY: 0
        run: shopify theme push --development --theme="****/${{ github.ref }}" --verbose
      - name: Deploy
        env:
          # Password generated from Theme Access app
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.STAGING_SHOPIFY_THEME_ACCESS_PASSWORD }}
          SHOPIFY_CLI_TTY: 0
        run: shopify theme push --development --theme="****/${{ github.ref }}" --verbose | Out-File -FilePath .\output.txt
      - name: Get Theme ID and Preview Link
        run: $preview_notice = Get-Content -Path ./output.txt | Select-String "View your theme:" -Context 0,1; $preview_notice -match '.+\/\?preview_theme_id=(.+)\Z'; $theme_id = $matches[1]; echo "theme_id=$theme_id" >> $GITHUB_OUTPUT ; echo "preview_notice=$preview_notice" >>$GITHUB_ENV
      - name: Add preview link notice
        run: echo '::notice title=Preview Link::${{ env.preview_notice }}'
```

On the `DELETEME Deploy (verbose)` step, this is the output in the GitHub Actions log:
```
Run shopify theme push --development --theme="****/refs/pull/269/merge" --verbose
  
2023-03-[30](https://github.com/****/****/actions/runs/4568356460/jobs/8063303431#step:6:31)T19:47:[33](https://github.com/****/****/actions/runs/4568356460/jobs/8063303431#step:6:34).697Z: Running command theme push
2023-03-30T19:47:33.705Z shopify:theme:push init version: @oclif/core@2.1.4 argv: [ '--development', '--theme=****/refs/pull/269/merge', '--verbose' ]
2023-03-30T19:47:33.867Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2023-03-30T19:47:33.868Z: Getting development theme...
2023-03-30T19:47:[34](https://github.com/****/****/actions/runs/4568356460/jobs/8063303431#step:6:35).389Z: Request to https://theme-kit-access.shopifyapps.com/cli/admin/api/unstable/themes.json completed in 504 ms
With response headers:
 - cache-control: no-cache
 - content-type: application/json; charset=utf-8
 - x-request-id: 1abd20b2-683c-4f71-8c99-5c54fc5ef9ba
    
╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  [[42](https://github.com/****/****/actions/runs/4568356460/jobs/8063303431#step:6:43)2] API request client error                                              │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

2023-03-30T19:47:34.500Z: Unable to log analytics event - no information on executed command
Error: Process completed with exit code 1.
```


When I run the same CLI command locally on Windows 10 Enterprise (`shopify theme push --development --theme="***/local/pipeline/testing" --verbose`) using the same Theme Access Password that's failing in the GitHub action, the CLI is able to successfully push the theme.
