### ISSUE TITLE
[Feature]: Multiple entries for `SHOPIFY_FLAG_STORE` and `SHOPIFY_CLI_THEME_TOKEN`

### ISSUE THREAD

**Issue by Jay-Plumb** [Shopify/cli#2629]
### What area(s) will this request affect?

Theme

### What type of change do you want to see?

New feature

### Overview

I have a CI pipeline that currently works for a staging store to automatically build out a preview theme. Ideally, I would like to specify multiple stores given we have multiple production stores for different regions e.g. US and EU so two stores.

Within a github action we have something along the lines of:

```
# production-us.yml
name: 'Deploy live (Production - US)'

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}
  SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_PRODUCTION_STORE_URL }}
  SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.PRODUCTION_SHOP_ACCESS_TOKEN }}
  SHOPIFY_CLI_TTY: 0
```

What I currently have to do is define the above file again and call it production-eu.yml and this is because I can only point to one store for `SHOPIFY_FLAG_STORE` and one access token for `SHOPIFY_CLI_THEME_TOKEN` each time. The downside to my approach is that I have to manually click to run the workflow as it is of type `workflow_dispatch` which is easily forgotten when you have two or more stores to update each time.

### Motivation

Solving for multiple stores to push out preview themes for CI actions in github

**Comment by Arkham** [comment]
Hey @Jay-Plumb, if I'm understanding this correctly you can also different envs for each command in a github action. For example you could have:
```
steps:
  - name: My first step
    run: echo "This is my secret $MY_SECRET"
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}
  - name: My second step
    run: echo "This is my secret $MY_SECRET"
    env:
      MY_SECRET: ${{ secrets.MY_OTHER_SECRET }}
```
