### ISSUE TITLE
[Bug]: Shopify Function CI Issue

### ISSUE THREAD

**Issue by Jay-Plumb** [Shopify/cli#2674]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension, Function

### Expected behavior

Hello, I am facing an issue when it comes to deploying in a CI context for a shopify function. I have the `SHOPIFY_CLI_PARTNERS_TOKEN` defined on the repo that was generated from the partners dashboard in the settings section and I have two scripts listed in my package.json to handle passing the correct client id.
```
    "deploy:staging": "npm run deploy -- --config staging",
    "deploy:production": "npm run deploy -- --config production"
```

I have manually pushed the shopify function to my staging app without issue so not too sure why I am seeing the error below. The output shows that the correct extension is being selected but deploy command fails.

### Actual behavior
```
Run npm run deploy:staging -- -f

> ci-cd-extension@1.0.0 deploy:staging
> npm run deploy -- --config staging -f


> ci-cd-extension@1.0.0 deploy
> shopify app deploy --config staging -f

╭─ info ───────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  Using shopify.app.staging.toml:                                             │
│                                                                              │
│    • Org:          pxl                                                │
│    • App:         Extensions [Staging]                              │
│                                                                              │
│   You can pass `--reset` to your command to reset your app configuration.    │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

╭─ warning ────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  `npm run deploy` now releases changes to users.                             │
│                                                                              │
│  All your extensions will be released to users, unless you add the           │
│  `--no-release` flag.                                                        │
│                                                                              │
│  Reference                                                                   │
│    • Simplified extension deployment [1]                                     │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
[1] https://shopify.dev/docs/apps/deployment/simplified-deployment


Releasing a new app version as part of Extensions [Staging]

Building function free-gift-with-machine...Building GraphQL types...
Bundling JS function...
Running javy...
Downloading javy v1.1.2 to /home/runner/.cache/binarycache/javy-v1.1.2
Done!

╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│                                                                              │
│    The Partners GraphQL API responded unsuccessfully with the HTTP status    │
│  200 and errors:                                                             │
│                                                                              │
│    [                                                                         │
│    {                                                                         │
│      "message": "Unexpected system error",                                   │
│      "extensions": {                                                         │
│        "code": "500"                                                         │
│      }                                                                       │
│    }                                                                         │
│  ]                                                                           │
│                                                                              │
│                                                                              │
│  To investigate the issue, examine this stack trace:                         │
│    at makeRequest (graphql-request/src/index.ts:441)                         │
│      throw new ClientError(                                                  │
│    at processTicksAndRejections (node:internal/process/task_queues:95)       │
│    at async debugLogResponseInfo                                             │
│    (@shopify/cli-kit/src/private/node/api.ts:26)                             │
│      response = await request                                                │
│    at async graphqlRequest                                                   │
│    (@shopify/cli-kit/src/public/node/api/graphql.ts:44)                      │
│      const response = await debugLogResponseInfo(                            │
│    at async handlePartnersErrors                                             │
│    (@shopify/app/src/cli/services/deploy/upload.ts:546)                      │
│      const result = await request()                                          │
│    at async uploadExtensionsBundle                                           │
│    (@shopify/app/src/cli/services/deploy/upload.ts:[170](https://github.com/pxl/extensions/actions/runs/5900228772/job/16042236053#step:2:183))                      │
│      const result: AppDeploySchema = await handlePartnersErrors(() =>        │
│      partnersRequest(mutation, options.token, variables))                    │
│    at task (@shopify/app/src/cli/services/deploy.ts:130)                     │
│      uploadExtensionsBundleResult = await uploadExtensionsBundle({           │
│    at async runTask                                                          │
│    (@shopify/cli-kit/src/private/node/ui/components/Tasks.tsx:45)            │
│      return await task.task(ctx, task)                                       │
│    at async runTasks                                                         │
│    (@shopify/cli-kit/src/private/node/ui/components/Tasks.tsx:79)            │
│      const subTasks = await runTask(task, ctx.current)                       │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

Error: Process completed with exit code 1.
```
### Reproduction steps

1. Select shopify function and generate token for SHOPIFY_CLI_PARTNERS_TOKEN
2. Create shopify function extension
3. Create a github action with the following content as an action

```
name: "CI/CD for Shopify extensions"
description: "For merges into dev and main, deploy the extension to the shopify partner apps for staging and production"

inputs:
  node-version:
    description: "Node Version to build the shopify theme with"
    default: 18

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install npm Dependencies
      run: |
        npm install
      shell: bash

    - name: Deploy (Staging)
      if: ${{ github.base_ref == 'dev' }}

      run: |
        npm run deploy:staging -- -f
      shell: bash

    - name: Deploy (Production)
      if: ${{ github.base_ref == 'main' }}

      run: |
        npm run deploy:production -- -f
      shell: bash
```
1. Call using a workflow:

```
# For merges into dev and main, deploy the extension to the shopify partner apps for staging and production
name: Deploy Extensions
on:
  pull_request:
    branches:
      - dev
      - main
    types: [closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Token from the Partner Dashboard - currently configured to work for the next 6 months and only selected the Checkout UI option.
  # A maximum of 2 tokens can be generated.(https://shopify.dev/docs/apps/tools/cli/ci-cd#generate-a-cli-authentication-token-in-the-partner-dashboard)
  SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged }}
    name: Deploy Extensions
    runs-on: ubuntu-latest

    steps:
      - id: deploy
        uses: pxl/github-actions/.github/actions/action-ui-extension-ci@main # This is a private repo so you will need to point to the action locally

```

### Operating System

Ubuntu   22.04.3   LTS

### Shopify CLI version (check your project's `package.json` if you're not sure)

"@shopify/cli": "3.48.0",     "@shopify/app": "3.48.0",

### Shell

bash
### Node version (run `node -v` if you're not sure)

v18.17
