### ISSUE TITLE
Config flag not being read and auth prompt getting skipped

### ISSUE THREAD

**Issue by ozziexsh** [Shopify/cli#2983]
Hi, we are trying to dockerize our local development environment but are running into issues with the shopify app cli. I've read through a ton of issues but can't find anyone with a similar story.

The container runs the command `shopify app dev --config=shopify.app.ozzie-dev.toml --tunnel-url=CLOUDFLARE_URL:3000`

1. The `--config` option does not appear to be respected. When running with this command and specifying a local `.toml` file I get the error "your project needs to be associated with an app". When running with the manual `--shop --client-id` params it no longer shows this error. Not a huge issue but curious if I'm misunderstanding the flag.
2. How are you supposed to authenticate without the oauth flow? I have gotten around it by authenticating on my host machine and then mounting the CLI config storage at `~/Library/Preferences/shopify-cli-kit-nodejs` to the container, but this is kinda hacky. I saw in the docs that you can pass a shopify partner token, but each partner account can only have 2 tokens at most so it isn't really scalable to multiple developers. Is there a way to do the oauth flow from a container? I get the error about running the cli non interactively so it doesn't even prompt with a URL.

Thanks in advance!

This is my `shopify.app.ozzie-dev.toml` file, placed at the root of the project:

```toml
# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sign-customiser-ozzie"
client_id = "redacted"
application_url = "https://km-develop-posts-rule.trycloudflare.com"
embedded = true
extension_directories = [ "packages/theme-app-extension" ]
web_directories = [ "packages/server" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_script_tags,write_script_tags,read_files,write_files,read_orders,read_themes,write_themes,read_content,write_content"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://km-develop-posts-rule.trycloudflare.com/auth",
  "https://km-develop-posts-rule.trycloudflare.com/auth/callback",
  "https://km-develop-posts-rule.trycloudflare.com/install/auth/callback",
  "https://km-develop-posts-rule.trycloudflare.com/install/auth"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sign-customiser-ozzie.myshopify.com"
```
