### ISSUE TITLE
[Bug]: yarn dev + Docker do not work together 

### ISSUE THREAD

**Issue by awd** [Shopify/cli#3002]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

The docker containers should be "up" and able to receive web traffic to the Rails app.

Rails app running Puma server on port 3000.

Visiting http://0.0.0.0:3000 manually loads the expected shopify app login screen.

```yaml
# docker-compose.yml

version: '3.2'

services:
  server:
    stdin_open: true
    tty: true
    build: .
    command: bundle exec puma -C config/puma.rb
    ports:
      - '3000:3000'
    env_file: .env
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      DATABASE_HOST: host.docker.internal
      WEBPACKER_DEV_SERVER_HOST: webpack
    volumes:
      - .:/usr/src/app
```

### Actual behavior

The docker-compose runs and boots all defined services, but the web app is unable to receive traffic, and the terminal throws an error line: Error forwarding web request: AggregateError

### Reproduction steps

1. run yarn dev
2. watch all processes boot up
3. view cloud flare url (....trycloudflare.com/extensions/dev-console)
4. click "App home"
5. nothing happens in browser
6. return to terminal and see error: Error forwarding web request: AggregateError

### Operating System

Mac OS. Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.48

### Shell

iTerm2

### Node version (run `node -v` if you're not sure)

v20.4.0

### What language and version are you using in your application?

ruby 3.1.2p20
