### ISSUE TITLE
[Bug]: SHOPIFY_CLI_TTY behavior inverted when CLI crashes (same issue as #3391)

### ISSUE THREAD

**Issue by seanwbarry** [Shopify/cli#3621]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

CLI does not prompt for user input. This is the same issue as #3391 

### Actual behavior

prompts for user input.
<img width="628" alt="tty issue" src="https://github.com/Shopify/cli/assets/12903479/f7465767-f561-4e04-90b9-806e3ad5a4b6">

### Verbose output

```shell
shopify theme push --path ./ --theme $DEV_THEME_ID --store $SHOPIFY_STORE
3s
+ shopify theme push --path ./ --theme $DEV_THEME_ID --store $SHOPIFY_STORE
╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  Failed to prompt:                                                           │
│                                                                              │
│  Push theme files to the published theme on                                  │
│  <store-url>?                                                                │
│                                                                              │
│  This usually happens when running a command non-interactively, for example  │
│   in a CI environment, or when piping input from another process.            │
│                                                                              │
│  To resolve this, specify the option in the command, or run the command in   │
│  an interactive environment such as your local terminal.
```

### Reproduction steps

1. create bitbucket account
2. create repo for theme in bitbucket
3. create this pipeline in repo:

```yaml
pipelines:
  default:
    - step:
        name: Deploy
        image: ruby:3.1
        services:
          - docker
        caches:
          - node
        script:
          - echo "Hello World!"
          - apt-get update
          - apt-get install -y nodejs npm
          - npm install -g @shopify/cli @shopify/theme
          - echo $(ls)
          - export SHOPIFY_FLAG_STORE=$SHOPIFY_STORE
          - export SHOPIFY_CLI_THEME_TOKEN=$SHOPIFY_CLI_THEME_TOKEN
          - export SHOPIFY_CLI_TTY=$SHOPIFY_CLI_TTY
          - shopify theme push --path ./ --theme $DEV_THEME_ID --store $SHOPIFY_STORE
```

4. set the environment variables as appropriate
5. run the pipeline

### Operating System

windows 11 (my system), however the build is running using docker

### Shopify CLI version (check your project's `package.json` if you're not sure)

latest
