### ISSUE TITLE
[Bug]: Unable to deploy app via `shopify app deploy` on github actions with `SHOPIFY_CLI_PARTNERS_TOKEN`

### ISSUE THREAD

**Issue by gupta-ji6** [Shopify/cli#3624]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App, Extension

### Expected behavior

The `shopify app deploy` command should run as expected when provided with a valid CLI token.

#### GitHub Action

<details><summary>`deploy.yml`</summary>
<p>

```yml
# Refer - https://shopify.dev/docs/apps/tools/cli/ci-cd
name: Deploy App
on: [deployment]

env:
  NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
  SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }} # Token from the Partner Dashboard
  SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }} # .env content after a deploy
  DOCKER_USERNAME: ${{ secrets.HARBOR_DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
  DOCKER_REGISTRY: ***
  APP_NAME: ***
  NODE_VERSION: 20.1.0

jobs:
  cancel:
    runs-on: [self-hosted]
    name: Cancel Previous Runs
    if: always()
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        if: github.ref != 'refs/heads/master'
        name: cancel old workflows
        id: cancel
        with:
          access_token: ${{ github.token }}
      - if: github.ref == 'refs/heads/master'
        name: Don't cancel old workflows
        id: dont_cancel
        run: |
          echo "Don't cancel old workflow"

  staging-deploy:
    runs-on: [self-hosted]
    needs: [cancel]
    continue-on-error: false
    name: Staging Deploy
    if: github.event.deployment.environment == 'staging'
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4
      - name: Setup Node v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install Dependencies & Setup Cache
        uses: bahmutov/npm-install@v1
      - name: Deploy
        env:
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
        run: npm run deploy:staging -- -f --source-control-url "$COMMIT_URL"
      - name: Mark Deployment Success on GitHub
        run: |
          curl --location --request POST 'https://api.github.com/repos/owner/repo/deployments/${{ github.event.deployment.id }}/statuses' \
          --header 'Authorization: token ${{ github.token }}' \
          --header 'Accept: application/vnd.github.everest-preview+json' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "environment": "staging",
            "state": "success"
          }'

```

</p>
</details> 

#### Logs
<details><summary>Stack Trace from Github Action logs</summary>
<p>

```bash
Run npm run deploy:staging -- -f --source-control-url "$COMMIT_URL"
  npm run deploy:staging -- -f --source-control-url "$COMMIT_URL"
  shell: /usr/bin/bash -e {0}
  env:
    NPM_RAZORPAY_TOKEN: ***
    GITHUB_ACCESS_TOKEN: ***
    SHOPIFY_CLI_PARTNERS_TOKEN: ***
  
    SHOPIFY_API_KEY: ***
    DOCKER_USERNAME: ***
    DOCKER_PASSWORD: ***
    DOCKER_REGISTRY: ***
    APP_NAME: ***
    NODE_VERSION: 20.1.0
    npm_config_cache: /home/runner/.npm
    COMMIT_URL: ***

> [dummy-app-name]@0.1.0 deploy:staging
> shopify app deploy --config staging -f --source-control-url ***

╭─ warning ────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  The flag `api-key` has been deprecated in favor of `client-id`              │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│                                                                              │
│  To investigate the issue, examine this stack trace:                         │
│    at tokenRequestErrorHandler                                               │
│    (@shopify/cli-kit/src/private/node/session/exchange.ts:17[4](https://github.com/razorpay/shopify-wallet/actions/runs/8477754319/job/23229073506#step:6:4))               │
│      return new InvalidRequestError()                                        │
│    at mapError (@shopify/cli-kit/src/public/node/result.ts:142)              │
│      return err(mapper(this.error))                                          │
│    at requestAppToken                                                        │
│    (@shopify/cli-kit/src/private/node/session/exchange.ts:1[5](https://github.com/razorpay/shopify-wallet/actions/runs/8477754319/job/23229073506#step:6:5)3)               │
│      const value =                                                           │
│      tokenResult.mapError(tokenRequestErrorHandler).valueOrBug()             │
│    at processTicksAndRejections (node:internal/process/task_queues:95)       │
│    at async exchangeCustomPartnerToken                                       │
│    (@shopify/cli-kit/src/private/node/session/exchange.ts:92)                │
│      const newToken = await requestAppToken('partners', token,               │
│      ['https://api.shopify.com/auth/partners.app.cli.access'])               │
│    at async ensureAuthenticatedPartners                                      │
│    (@shopify/cli-kit/src/public/node/session.ts:41)                          │
│      return (await exchangeCustomPartnerToken(envToken)).accessToken         │
│    at async fetchPartnersSession                                             │
│    (@shopify/app/src/cli/services/context/partner-account-info.ts:39)        │
│      const token = await ensureAuthenticatedPartners()                       │
│    at async ensureDeployContext                                              │
│    (@shopify/app/src/cli/services/context.ts:3[7](https://github.com/razorpay/shopify-wallet/actions/runs/8477754319/job/23229073506#step:6:7)0)                            │
│      const partnersSession = await fetchPartnersSession()                    │
│    at async deploy (@shopify/app/src/cli/services/deploy.ts:4[9](https://github.com/razorpay/shopify-wallet/actions/runs/8477754319/job/23229073506#step:6:9))              │
│      let {app, identifiers, partnersApp, token, release} = await             │
│      ensureDeployContext(options)                                            │
│    at run (@shopify/app/src/cli/commands/app/deploy.ts:[10](https://github.com/razorpay/shopify-wallet/actions/runs/8477754319/job/23229073506#step:6:10)2)                  │
│      await deploy({                                                          │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯


Error: Process completed with exit code 1.
```

</p>
</details> 

### Verbose output

```shell
TBD - will update it soon by adding a verbose flag.
```

### Reproduction steps

1. Create a GitHub Action for deployment as per https://shopify.dev/docs/apps/tools/cli/ci-cd#step-3-integrate-shopify-cli-into-your-pipeline 
2. Generate `SHOPIFY_CLI_PARTNERS_TOKEN` & add to repo secrets.
3. Trigger github actions which run `shopify app deploy` command.

### Operating System

macOS 13.6.5

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.56.2

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v20.1.0

### What language and version are you using in your application?

Node 20, React 18
