### ISSUE TITLE
Webhooks config issue in `shopify.app.toml`

### ISSUE THREAD

**Issue by Xmaster6y** [Shopify/cli#5505]
## TL;DR

Impossible to deploy a config with `/webhooks` URI or with both compliance and regular topics.

### `/webhooks`

The config I'm used to use:

```toml
[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update", "app/uninstalled" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
```

Yields the error:

```
╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  App configuration is not valid                                              │
│  Validation errors in shopify.app.dev.toml:                                  │
│                                                                              │
│  • [webhooks.subscriptions.0.uri]: URI isn't correct URI format of           │
│  https://, pubsub://{project}:topic or Eventbridge ARN                       │
│                                                                              │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
```

### Https

The config:

```toml
[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update", "app/uninstalled" ]
  uri = "https://programming-neighbor-we-transmit.trycloudflare.com/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
```

Yields the error:

```
╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  Version couldn't be created.                                                │
│                                                                              │
│  webhooks                                                                    │
│                                                                              │
│  Validation errors                                                           │
│    • Unexpected key(s) were found.                                           │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
```

same for:

```toml
[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update", "app/uninstalled" ]
  uri = "https://programming-neighbor-we-transmit.trycloudflare.com/webhooks"

  [[webhooks.subscriptions]]
  uri = "https://programming-neighbor-we-transmit.trycloudflare.com/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
```

### What works

The configs that work:

```toml
[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "https://programming-neighbor-we-transmit.trycloudflare.com/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
```
